### ISSUE TITLE
请教一下为何不建议使用IP-ASN分流？

### ISSUE THREAD

**Issue by BugGust** [getsomecat/GetSomeCats#36]
小小萌新求教，dalao写的“Surge新手从开始使用到退款”对我帮助很大，我在参考您的[SurgePro.conf](https://github.com/getsomecat/GetSomeCats/blob/Surge/SurgePro.conf)手搓配置时看到您在692行里写到“# Surge 作者有提到不建议也没有必要使用 IP-ASN 类型规则进行地区分流”而我在surge官方的手册和社区中并没有找到上面所说的内容，所以想请教一下dalao具体原因。
以下是我的个人看法———————————
我使用的是chinaASN替代geoip CN的规则，因为第三方geoip规则在surge下自动更新的频率是每周(且不能自定义频率)而使用RULE-SET的ASN规则不仅可以自行调整更新时间，数据量还比geoip更少，[VirgilClyne](https://github.com/VirgilClyne/GetSomeFries/issues/25)也回答过更新及时的ASN规则不比某些geoip库差，所以我认为使用ASN进行地区分流规则更适合我。

**Comment by Zeaphyou** [comment]
这个似乎是官方社区开发者回答人家的时候还是在tg群里这么提到过一嘴的事吧，而且我和薯条也讨论过这个问题，就我自己用的来说，也加了薯条的asn，但是实际上还是底下接了一个geoip cn的，只能说可以替代，没什么大问题，偶尔有个别不准的情况，但是几乎没影响，看个人喜好。

**Comment by BugGust** [comment]
> 这个似乎是官方社区开发者回答人家的时候还是在tg群里这么提到过一嘴的事吧，而且我和薯条也讨论过这个问题，就我自己用的来说，也加了薯条的asn，但是实际上还是底下接了一个geoip cn的，只能说可以替代，没什么大问题，偶尔有个别不准的情况，但是几乎没影响，看个人喜好。

感谢dalao回答了，其实在之前我也在网上检索过相关信息，在这里[ASN分流](https://github.com/IrineSistiana/mosdns/discussions/729#discussioncomment-7218459)(虽然和surge关系不大，但可以参考)的回答下了解到ASN对比geoip细分还是geoip库更好，毕竟不是只有国内用户，其他地区用户也会有分流需求的。但如果只是单纯使用ASN来区分国内和非国内ip进行分流还是可行的，策略上我是CNgeosite+CNASN进行国内外分流，考虑到geoip和ASN会有重复的问题，不太清楚dalao为何如此配，请问有什么特别的优势吗？还是说只是个人爱好呢？

**Comment by Zeaphyou** [comment]
纯个人爱好而已，实际上二者选一个就行了的。

**Comment by BugGust** [comment]
> 纯个人爱好而已，实际上二者选一个就行了的。

好的，明白了，谢谢dalao
